owner: slawuwc # Your GitHub organization or username, where this repository lives
repo: slaw-status # The name of this repository

sites:
    - name: SLAW Main Site
      url: https://slawuwc.org
      maxRedirects: 4
    - name: SLAW Main Site (www)
      url: https://www.slawuwc.org
      maxRedirects: 5
    # - name: SLAW Backup Site
    #   url: https://slaw.leranjun.repl.co
    #   maxRedirects: 5
    - name: SLAW Discover
      url: https://discover.slawuwc.org

status-website:
    # Add your custom domain name, or remove the `cname` line if you don't have a domain
    # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
    cname: status.slawuwc.org
    # baseUrl: /your-repo-name
    favicon: https://discover.slawuwc.org/favicon-32x32.png
    logoUrl: https://discover.slawuwc.org/img/logo.png
    name: SLAW Status
    navbar:
        - title: Status
          href: /
        - title: GitHub
          href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
